apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-profile-operator
  namespace: security-ops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-profile-operator
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["security.istio.io"]
    resources: ["peerauthentications", "authorizationpolicies"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["cilium.io"]
    resources: ["ciliumnetworkpolicies"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["security.demo.cypher"]
    resources: ["securityprofiles"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-profile-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: security-profile-operator
subjects:
  - kind: ServiceAccount
    name: security-profile-operator
    namespace: security-ops

