apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # App
  - ../../apps/hello-nginx/overlays/dev

  # Service mesh security policies (assumes Istio installed)
  - ../../platform/istio/security/hello-nginx

  # CNI security policies (assumes Cilium installed)
  - ../../platform/cilium/policies/hello-nginx

  # Admission policies (assumes Kyverno installed)
  - ../../policies/kyverno

  # Operator + CRD (optional pattern demo)
  - ../../operators/security-profile-operator/manifests
  - ../../operators/security-profile-operator/crd/examples/hello-nginx-securityprofile.yaml

