apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-baseline-pod-security
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: disallow-privilege-escalation
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - istio-system
                - kyverno
                - argocd
                - security-ops
      validate:
        message: "Containers must set securityContext.allowPrivilegeEscalation=false"
        pattern:
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
    - name: require-run-as-non-root
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - istio-system
                - kyverno
                - argocd
                - security-ops
      validate:
        message: "Containers must set securityContext.runAsNonRoot=true"
        pattern:
          spec:
            containers:
              - securityContext:
                  runAsNonRoot: true
    - name: drop-all-capabilities
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - istio-system
                - kyverno
                - argocd
                - security-ops
      validate:
        message: "Containers must drop ALL Linux capabilities"
        pattern:
          spec:
            containers:
              - securityContext:
                  capabilities:
                    drop:
                      - ALL
    - name: require-seccomp-runtime-default
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - istio-system
                - kyverno
                - argocd
                - security-ops
      validate:
        message: "Pods must set spec.securityContext.seccompProfile.type=RuntimeDefault"
        pattern:
          spec:
            securityContext:
              seccompProfile:
                type: RuntimeDefault

