apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-security
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_ME_REPO_URL
    targetRevision: main
    path: platform/istio/security/hello-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

