apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hello-nginx.yaml
  - policies.yaml
  - istio-security.yaml
  - cilium-policy.yaml
  - operator.yaml
  - securityprofile-example.yaml

