apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  namespace: hello-nginx
  labels:
    app.kubernetes.io/name: hello-nginx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hello-nginx
  ports:
    - name: http
      port: 80
      targetPort: http

