apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/hello-nginx/overlays/prod
  - ../../platform/istio/security/hello-nginx
  - ../../platform/cilium/policies/hello-nginx
  - ../../policies/kyverno
  - ../../operators/security-profile-operator/manifests
  - ../../operators/security-profile-operator/crd/examples/hello-nginx-securityprofile.yaml

